### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by zachlatta** [istx25/pistachio#6]
The README has a badge mentioning the inclusion of a license, but when clicking on it, I get a 404.

**Comment by istx25** [comment]
Whoops! I'll fix that right away. Thanks for catching that. :smiley:

**Comment by zachlatta** [comment]
Sounds good!

--
Zach Latta
Executive Director of hackEDU <https://hackedu.us>
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
:+1:

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta
